### ISSUE TITLE
'expires_at' value is not properly calculated

### ISSUE THREAD

**Issue by marauzog** [auth0-blog/angular-auth0-aside#2]
https://github.com/auth0-blog/angular-auth0-aside/blob/d696edbefcda0ac024b429c4cc8b5bed3bef0d2c/src/app/auth/auth.service.ts#L71

The correct line would be:
`localStorage.setItem('expires_at', Date.now() + authResult.expiresIn);`

authResult comes with the token duration (field 'expiresIn'), but the 'expiresAt' variable represents the time at which the token expires.

**Comment by kmaida** [comment]
This has been corrected. The `expiresAt` value used to be returned, but it has since been changed to be `expiresIn`.
